### ISSUE TITLE
SROS2 demo not yet working with RTI Connext

### ISSUE THREAD

**Issue by ruffsl** [ruffsl/ros2_docker_demos#1]
Following the workaround exhibited from OSRF's CI for installing RTI Connext with ROS2 Bouncy, it seems I've still hit a snag relating to the differences between the OpenSSL RTI currently releases against, vs that which comes with Ubuntu 18.04:

```
$ docker-compose up
Starting sros2_talker_1     ... done
Attaching to sros2_talker_1, sros2_listener_1
talker_1    | ROS_DISTRO was set to 'melodic' before. Please make sure that the environment does not mix paths from different distributions.
talker_1    | ###############################################################################
talker_1    | 
talker_1    |          (c) Copyright, Real-Time Innovations, All rights reserved.            
talker_1    |                                                                                
talker_1    |                            RTI Connext DDS 5.3.1                       
talker_1    | 
talker_1    | ###############################################################################
talker_1    | RTI Data Distribution Service EVAL License issued ... For non-production use only.
talker_1    | Expires on ... See www.rti.com for more information.
talker_1    | [CREATE Participant]RTIOsapiLibrary_open:error opening library libnddssecurity.so: /opt/rti/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0/libnddssecurity.so: undefined symbol: CRYPTO_set_locking_callback
talker_1    | [CREATE Participant]DDS_DomainParticipantTrustPlugins_initialize:!failed to load library
talker_1    | [CREATE Participant]DDS_DomainParticipant_createI:!create builtin trust plugins support
talker_1    | [CREATE Participant]DDS_DomainParticipantFactory_create_participant_disabledI:!create participant
talker_1    | DDSDomainParticipant_impl::create_disabledI:!create participant
talker_1    | DDSDomainParticipant_impl::createI:!create participant
talker_1    | DomainParticipantFactory_impl::create_participant():!create failure creating participant
talker_1    | terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
talker_1    |   what():  failed to initialize rcl node: failed to create participant, at /tmp/binarydeb/ros-bouncy-rmw-connext-shared-cpp-0.5.1/src/node.cpp:255, at /tmp/binarydeb/ros-bouncy-rcl-0.5.0/src/rcl/node.c:336
sros2_talker_1 exited with code 250
```

For replication of error, see demo readme here: https://github.com/ruffsl/ros2_docker_demos/blob/dc8d97c4afc35ab2fde7720267e8ef4b31e24d12/sros2/README.md

References:
[ros2/ci/linux_docker_resources/entry_point.sh.sh](https://github.com/ros2/ci/blob/b0bf9856f073a1d52773a78601cbc50afc553f0d/linux_docker_resources/entry_point.sh)  
[ros2/ci/linux_docker_resources/rti_web_binaries_install_script.py](https://github.com/ros2/ci/blob/49377c17b2d1e7b37bf8596df66986a1c6042121/linux_docker_resources/rti_web_binaries_install_script.py)  

Perhaps someone might spot my installation setup error. ping @mikaelarguedas ?

**Comment by mikaelarguedas** [comment]
you need to install the connext security plugins as well as the version of openssl they ship in their archives.

based on osrf/ros2:bouncy-full:
- copy / mount your rti license file in the container
- install connext and associates ROS packages
```
apt update && apt install -y ros-bouncy-rmw-connext-cpp
```
- Download the connext archive with the security plugins from the RTI website:
`wget https://s3.amazonaws.com/RTI/Bundles/5.3.1/Evaluation/rti_connext_dds_secure-5.3.1-eval-x64Linux3gcc5.4.0.tar.gz`

- Extract the contents:
```
tar xvf rti_connext_dds_secure-5.3.1-eval-x64Linux3gcc5.4.0.tar.gz
tar xvf openssl-1.0.2n-target-x64Linux3gcc5.4.0.tar.gz
```
- Install the security plugins:
```
/opt/rti.com/rti_connext_dds-5.3.1/bin/rtipkginstall openssl-1.0.2n-5.3.1-host-x64Linux.rtipkg
/opt/rti.com/rti_connext_dds-5.3.1/bin/rtipkginstall rti_security_plugins-5.3.1-eval-x64Linux3gcc5.4.0.rtipkg
```
- Setup environment:
```
export RTI_LICENSE_FILE=/root/rti_license.dat
# add RTI's openssl to library path and path
export LD_LIBRARY_PATH=/root/openssl-1.0.2n/x64Linux3gcc5.4.0/release/lib:{LD_LIBRARY_PATH}
export PATH=/root/openssl-1.0.2n/x64Linux3gcc5.4.0/release/bin:${PATH}
source /opt/rti.com/rti_connext_dds-5.3.1/resource/scripts/rtisetenv_x64Linux3gcc5.4.0.bash
export RMW_IMPLEMENTATION=rmw_connext_cpp
```

- Bootstrap the SROS2 demo:
```
mkdir ~/sros2_demo
cd ~/sros2_demo
source /opt/ros/bouncy/setup.bash
ros2 security create_keystore demo_keys
ros2 security create_key demo_keys talker
ros2 security create_key demo_keys listener
export ROS_SECURITY_ROOT_DIRECTORY=~/sros2_demo/demo_keys
export ROS_SECURITY_ENABLE=true
export ROS_SECURITY_STRATEGY=Enforce
```
- Run the demo:
```
ros2 run demo_nodes_cpp talker
```

**Comment by ruffsl** [comment]
Thanks for the complete write up @mikaelarguedas ! I had the majority of this ported to docker and compose files already in the demo folder with the readme, but thanks to this I spotted what I had forgotten, i.e to append to the `LD_LIBRARY_PATH` `PATH` environment variables. See: https://github.com/ruffsl/ros2_docker_demos/commit/da1a2e1e5e775794be65079b3daff92eda32f95b . So this is working now!

Oddly enough, using security seems to work even when the network driver for all containers is set to "host", i.e when GUIDs of the two participants to collide, regardless if `ipc: host` or not in docker. This is counter to the observations I made in my answers.ros question:
[ROS2 connectivity across Docker containers via Host Driver](https://answers.ros.org/question/296828/ros2-connectivity-across-docker-containers-via-host-driver/)

Perhaps when secure transport is used, the issue with IPC or discovery no longer exhibits itself? This behave similarly for both `rmw_connext_cpp` and `rmw_fastrtps_cpp`. Is IPC currently disabled by venders when security is enabled?

Additionally, what currently is preventing `rmw_connext_cpp` and `rmw_fastrtps_cpp` from intercommunicating when security is enabled, a deviation from the spec still? All the comantoral combination of rwm implementations (including `rmw_opensplice_cpp` with some warnings) seem to intercommunicate fine without security.

**Comment by mikaelarguedas** [comment]
> Additionally, what currently is preventing rmw_connext_cpp and rmw_fastrtps_cpp from intercommunicating when security is enabled, a deviation from the spec still?

Yeah, I use the same defaults (for key size, encryption etc) but they still don't talk.
Last time I checked with the various parties they were aware of the issue and OMG was putting together a set of tests for all vendors to prove interoperability. That was a while ago I didn't get a chance to follow up on it

> Perhaps when secure transport is used, the issue with IPC or discovery no longer exhibits itself? This behave similarly for both rmw_connext_cpp and rmw_fastrtps_cpp. Is IPC currently not used by fenders when security is enabled?

Hmm that;s a good question. I don't know of the top of my head but that would be worth looking into

**Comment by ruffsl** [comment]
Whats a good way of checking if OS level IPC is being used for ros2 or DDS in general? I've combed around community.rti.com and haven't found anything definite. Is there a ROS2 unit test for this somewhere?

**Comment by ruffsl** [comment]
I've answered my answers.ros question:
[ROS2 connectivity across Docker containers via Host Driver](https://answers.ros.org/question/296828/ros2-connectivity-across-docker-containers-via-host-driver/), and `rmw_connext_cpp` seems to be working. As for `rmw_fastrtps_cpp`, not so much, yet I feel that may be a security artifact issue with keymint, given sros2 default scripts work: https://github.com/ruffsl/ros2_docker_demos/issues/2
